---

- name: 'Create dest path'
  file:
    path: "{{ vm_info.datastore_path }}/{{ clone_to }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Copy files'
  copy:
    src: "{{ item }}"
    dest: "{{ vm_info.datastore_path }}/{{ clone_to }}/"
    remote_src: true
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - "{{ vmx_file.path }}"
    - "{{ vm_info.datastore_path }}/{{ vm_name }}/{{ vmx_disk }}.vmdk"
    - "{{ vm_info.datastore_path }}/{{ vm_name }}/{{ vmx_disk }}-sesparse.vmdk"
  vars:
    vmx_file: "{{ vm_file.files | first }}"
    vmx_disk: "{{ vm_file_content['content'] | b64decode | regex_findall(regex_disk) | first }}"
    regex_disk: '(?:sata|scsi)0:0\.fileName\s=\s\"([\S\s][^\.]+[0-9]{6,6})'

- name: 'Delete references by cloned machine, will be auto recreated'
  lineinfile:
    path: "{{ vm_info.datastore_path }}/{{ clone_to }}/{{ vmx_file_name }}"
    state: absent
    regexp: "{{ item }}"
  vars:
    vmx_file_name: "{{ (vm_file.files | first ).path.split('/')[-1] }}"
  loop:
    - "sched.swap.derivedName.+"
    - "ethernet0.generatedAddress.+"
    - "ethernet0.addressType.+"
    - "uuid.location.+"
    - "uuid.bios.+"

- name: 'Change VM name and ID'
  lineinfile:
    path: "{{ vm_info.datastore_path }}/{{ clone_to }}/{{ vmx_file_name }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  vars:
    vmx_file_name: "{{ (vm_file.files | first ).path.split('/')[-1] }}"
  loop:
    - line: 'machine.id="{{ clone_to }}"'
      regexp: 'machine.id.+'
    - line: 'displayName = "{{ clone_to }}"'
      regexp: 'displayName.+'

- name: 'Change parentFileNameHint on VMDK'
  lineinfile:
    path: '{{ vm_info.datastore_path }}/{{ clone_to }}/{{ vmx_disk }}'
    line: '\1{{ vm_info.datastore_path }}/{{ vm_name }}/\2'
    regexp: '(parentFileNameHint=\")(.+)'
    backrefs: yes
  vars:
    vmx_disk: "{{ vm_file_content['content'] | b64decode | regex_findall(regex_disk) | first }}"
    regex_disk: '(?:sata|scsi)0:0\.fileName\s=\s\"([\S\s][^\.]+[0-9]{6,6}\.vmdk)'
