---

- name: 'Unregister VM'
  command: 'vim-cmd vmsvc/unregister {{ vm_info.id }}'
  changed_when: true

- name: 'Delete VM data'
  file:
    path: "{{ vm_info.datastore_path }}/{{ vm_info.path }}"
    state: 'absent'
