---

- name: 'Get info about cloned VM'
  include_tasks: 'get_vm_info_from_esxi.yml'

- name: 'Find VMX file'
  find:
    paths: "{{ vm_info.datastore_path }}/{{ vm_name }}"
    patterns: "*.vmx"
  register: 'vm_file'

- name: 'Get VMX file content'
  slurp:
    src: "{{ file.path }}"
  register: vm_file_content
  vars:
    file: "{{ vm_file.files | first }}"
